# Generated by Django 4.1.7 on 2023-04-13 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="book",
            old_name="subtite",
            new_name="subtitle",
        ),
    ]
