# Generated by Django 4.1.7 on 2023-04-13 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0002_rename_subtite_book_subtitle"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="content",
            field=models.TextField(blank=True, null=True),
        ),
    ]
